In [19]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [20]:
import pandas as pd
import numpy as np
from reformat_data import *

In [23]:
data_people = people_reformat(r"/mnt/Data1/Python_Projects/Pure-Python/P5/01-Thesis/data/Shiraze94_fa/People.xlsx")
data_family = family_reformat(r"/mnt/Data1/Python_Projects/Pure-Python/P5/01-Thesis/data/Shiraze94_fa/Family.xlsx")
data_trips = trips_reformat(r"/mnt/Data1/Python_Projects/Pure-Python/P5/01-Thesis/data/Shiraze94_fa/Trips.xlsx")

In [24]:
data_trips

,trip_code,questionnaire_code,person_number,home_area_code,home_region_code,origin_area_code,origin_region_code,destination_area_code,destination_region_code,trip_purpose,travel_mode,start_hour,start_minute,hourly_correction_factor,trip_distance,home_based,previous_trip_code
0,120670,11010014,1,252,14,252,14,128,7,visit_offices,private_car,10,15,1.7,8499.15,home_start,0
1,120671,11010014,1,252,14,128,7,252,14,return_home,private_car,14,30,1.7,7693.01,home_end,120670
2,100368,11010080,1,171,14,171,14,170,14,recreation_or_pilgrimage,taxi,7,30,1.0,2421.68,home_start,0
3,100370,11010080,1,171,14,170,14,171,14,return_home,taxi,8,35,1.0,1677.50,home_end,100368
4,100371,11010080,1,171,14,171,14,6,1,shopping,city_bus,12,37,1.0,7807.36,home_start,100370
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93936,107679,32318109,1,27,1,30,1,27,1,return_home,bicycle,18,30,1.0,1141.41,home_end,107678
93937,107672,32318110,1,27,1,27,1,30,1,education,city_bus,9,30,1.0,1268.87,home_start,0
93938,107673,32318110,1,27,1,30,1,27,1,return_home,taxi,14,0,1.0,1141.41,home_end,107672
93939,107674,32318110,1,27,1,27,1,30,1,education,city_bus,17,20,1.0,1268.87,home_start,107673
93940,107675,32318110,1,27,1,30,1,27,1,return_home,city_bus,19,45,1.0,1141.41,home_end,107674

In [29]:
list(data_people.columns), list(data_family.columns), list(data_trips.columns)

(['questionnaire_code',
  'person_number',
  'gender',
  'age',
  'job',
  'working',
  'driving_license',
  'education_level',
  'home_area_code',
  'home_region_code'],
 ['questionnaire_code',
  'family_members_count',
  'total_vehicles_count',
  'bicycles_24inch_or_larger_count',
  'motorcycles_count',
  'private_cars_count',
  'pickup_trucks_count',
  'taxis_count',
  'other_vehicles_count',
  'private_car_1',
  'private_car_2',
  'private_car_3',
  'private_car_4',
  'home_area_code',
  'home_region_code',
  'correction_factor',
  'expansion_factor'],
 ['trip_code',
  'questionnaire_code',
  'person_number',
  'home_area_code',
  'home_region_code',
  'origin_area_code',
  'origin_region_code',
  'destination_area_code',
  'destination_region_code',
  'trip_purpose',
  'travel_mode',
  'start_hour',
  'start_minute',
  'hourly_correction_factor',
  'trip_distance',
  'home_based',
  'previous_trip_code'])