In [1]:
%load_ext autoreload
%autoreload 2
import pandas as pd
import numpy as np
from delete_distance_from_centerline import Delete_Distance_From_Centerline

In [13]:
main_file = r"D:\All Python\Pure-Python\P2\12-Work-GITI\09-temp\raw_data\New_G.csv"

dataloader = Delete_Distance_From_Centerline(main_file=main_file, left_bound=0.3, right_bound=0.3)
dataloader.fit()
dataloader.save_file(r"D:\All Python\Pure-Python\P2\12-Work-GITI\09-temp\raw_data")

d:\All Python\Pure-Python\P2\12-Work-GITI\09-temp\delete_distance_from_centerline.py:137: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  result.fillna("", inplace=True)

'D:\\All Python\\Pure-Python\\P2\\12-Work-GITI\\09-temp\\raw_data\\delete_distance_from_centerline_New_G.csv'

In [7]:
dd = dataloader.raw_data_main
dd

,No,Distance,L38,L37,L36,L35,L34,L33,L32,L31,...,R30,R31,R32,R33,R34,R35,R36,R37,R38,end
0,1.0,107333.01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2.0,107360.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3.0,107400.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1401,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1402,702.0,118180.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1403,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1404,703.0,118200.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1405,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:

dataloader.fit()

d:\All Python\Pure-Python\P2\12-Work-GITI\09-temp\delete_distance_from_centerline.py:137: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  result.fillna("", inplace=True)

,No,Distance,L38,L37,L36,L35,L34,L33,L32,L31,...,R30,R31,R32,R33,R34,R35,R36,R37,R38,end
0,1.0,107333.01,,,,,,,,,...,,,,,,,,,,
1,,,,,,,,,,,...,,,,,,,,,,
2,2.0,107360.0,,,,,,,,,...,,,,,,,,,,
3,,,,,,,,,,,...,,,,,,,,,,
4,3.0,107400.0,,,,,,,,,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1401,,,,,,,,,,,...,,,,,,,,,,
1402,702.0,118180.0,,,,,,,,,...,,,,,,,,,,
1403,,,,,,,,,,,...,,,,,,,,,,
1404,703.0,118200.0,,,,,,,,,...,,,,,,,,,,
1405,,,,,,,,,,,...,,,,,,,,,,

In [9]:
d = dataloader.CSDP

In [10]:
d

,No,Distance,L38,L37,L36,L35,L34,L33,L32,L31,...,R30,R31,R32,R33,R34,R35,R36,R37,R38,end
0,1.0,107333.01,,,,,,,,,...,,,,,,,,,,
1,,,,,,,,,,,...,,,,,,,,,,
2,2.0,107360.0,,,,,,,,,...,,,,,,,,,,
3,,,,,,,,,,,...,,,,,,,,,,
4,3.0,107400.0,,,,,,,,,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1401,,,,,,,,,,,...,,,,,,,,,,
1402,702.0,118180.0,,,,,,,,,...,,,,,,,,,,
1403,,,,,,,,,,,...,,,,,,,,,,
1404,703.0,118200.0,,,,,,,,,...,,,,,,,,,,
1405,,,,,,,,,,,...,,,,,,,,,,

In [ ]:
dd